### ISSUE TITLE
Throwing error: TypeError: this.env.adapter.prompt(...).then is not a function

### ISSUE THREAD

**Issue by Hosar** [HistoireDeBabar/generator-universal-react-and-redux#1]
Is throwing this error when trying to use the generator:
- yo universal-react-and-redux

events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/usr/local/lib/node_modules/generator-universal-react-and-redux/node_modules/yeoman-generator/lib/base.js:240:45)
    at module.exports.yeoman.Base.extend.prompting (/usr/local/lib/node_modules/generator-universal-react-and-redux/generators/app/index.js:47:17)

**Comment by HistoireDeBabar** [comment]
Hey,

Thanks for raising this.  Can you check you're Yo version please and see what it is.  I've seen this issue before with other generators (e.g. [here](https://github.com/FountainJS/generator-fountain-webapp/issues/56)).  I'm currently running 3.9.5 and it's running okay here.

Thanks again!
